# -*- coding: utf-8 -*-
"""Datamuse API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g9s9y0pWw4FrjMrXMsVDBvXvqZfzl7ju
"""

import json
import requests
import statistics

from google.colab import drive
drive.mount("/content/drive")

folder = "/content/drive/MyDrive/TFG/Sentence-transformers/data/en/"
files = ["seen.json", "unseen.json", "desc.json"]


for file in files:
  f = open(folder+file, "r")
  output_file = open(file+"_Datamuse_predictions.txt", "w")

  eval_data = json.load(f)

  precision_1 = 0
  precision_10 = 0
  precision_100 = 0
  median_and_variance = []
  predicted_words = []

  for i in eval_data:
    key_word = i['word']
    output_file.write(key_word + " ||| ") 
    definition = i['definitions']
    definition = definition.replace(' ', "%20")   

    url = "http://api.datamuse.com/words?ml=" + definition
    predictions = requests.get(url).json()

    precision = 0
    found = False
    for prediction in predictions:
      if isinstance(prediction, dict):
        precision = precision + 1
        pred_word = prediction['word']
        output_file.write(pred_word + ", ")
        if pred_word == key_word:
          found = True
          predicted_words.append(pred_word)
          break
    output_file.write("\n") 
    if found:
      median_and_variance.append(precision-1)
      if precision <= 1:
        precision_1 = precision_1 + 1
      if precision <= 10:
        precision_10 = precision_10 + 1
      if precision <= 100:
        precision_100 = precision_100 + 1


  prec1 = precision_1 / len(eval_data)
  prec10 = precision_10 / len(eval_data)
  prec100 = precision_100 / len(eval_data)
  mediana = statistics.median(median_and_variance)
  varianza = statistics.variance(median_and_variance)

  print(file)
  print("Mediana: " + str(mediana))
  print("Precision P@1: {:.2%}".format(prec1))
  print("Precision P@10: {:.2%}".format(prec10))
  print("Precision P@100: {:.2%}".format(prec100))
  print("Varianza: " + str(varianza))
  print(predicted_words)
  

  f.close()
  output_file.close()

from google.colab import drive
drive.mount('/content/drive')